Fix bug in subdomain verification
When there is verification error and "reason" is present, no reply was
returned to client causing django exception:

ValueError: The view pyi2phosts.postkey.views.subdomain didn't return an
HttpResponse object.